### ISSUE TITLE
6 Button Keypads scene buttons not functioning

### ISSUE THREAD

**Issue by jbarneson** [teharris1/insteon2#1]
originally reported in your post on HA community: https://community.home-assistant.io/t/new-insteon-version-for-beta-testing/184489/49

creating an issue instead of continually forking the thread. Here was my latest error message I'm getting after you updated the source: 

`2020-04-12 07:23:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140201181221200] tuple index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/config/custom_components/insteon2/switch.py", line 29, in async_turn_on
    await self._insteon_device.async_on(group=self._insteon_device_group.group)
  File "/usr/local/lib/python3.7/site-packages/pyinsteon/device_types/dimmable_lighting_control.py", line 364, in async_on
    return await self._handlers[SET_LEDS_COMMAND].async_send(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyinsteon/handlers/to_device/set_leds.py", line 66, in async_send
    group1, group2, group3, group4, group5, group6, group7, group8
  File "/usr/local/lib/python3.7/site-packages/pyinsteon/handlers/to_device/set_leds.py", line 11, in _bitmask
    val = 1 if args[group] else 0
IndexError: tuple index out of range`

**Comment by teharris1** [comment]
I updated the pyinsteon module to fix this issue. In order to see the update you need to reinstall pyinsteon.  Let me know how the fix works. I was able to fake my 8 button dimmer to appear like a 6 button switch to test it so I am pretty confident it will work.

**Comment by jbarneson** [comment]
installing with, assuming it's not a new build? (I also upgraded my HA image, so it's a clean install of pyinsteon)

`docker exec -it --user=root homeassistant pip3 install --upgrade https://github.com/teharris1/pyinsteon/archive/release1.zip`

**Comment by teharris1** [comment]
Correct, not a new build but a commit to the "release1" branch. I am keeping the "release1" branch open until we get this solid.

**Comment by jbarneson** [comment]
ooh, sorry sir. Really odd behavior now. Logs below. 

On the plus side, i am seeing the keybad button respond to a switch toggle initiated from HA, but two new symptoms i'm seeing:

1) when i turn on any of the keypad buttons, the physical button on the device turns on, the logical switch in HA reflects the updated state momentarily, but then resets back to OFF

2) when i turn on any subsequent keypad buttons, the physical button on the device turns on, but the previous physical button turns off. So if i turn on keypad_A from HA, A lights up, when i turn on keypad_B from HA, B lights up, but then A turns off

log snippets: 
`

[keypad_a]

2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.topics] Topic: send.extended_get_set.direct data: {'address': 32fe95, 'priority': 5, 'data1': 1, 'data2': 9, 'data3': 4, 'data4': 0, 'data5': 0, 'data6': 0, 'data7': 0, 'data8': 0, 'data9': 0, 'data10': 0, 'data11': 0, 'data12': 0, 'data13': 0, 'data14': 0}
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.topics] Topic: send_message.extended_get_set data: {'msg': msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.04.00.00.00.00.00.00.00.00.00.00.c4, 'priority': 5}
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.messages] TX: msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.04.00.00.00.00.00.00.00.00.00.00.c4
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.04.00.00.00.00.00.00.00.00.00.00.c4, ack: 0x06
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.topics] Topic: ack.32fe95.extended_get_set.direct data: {'cmd1': 46, 'cmd2': 0, 'user_data': 01.09.04.00.00.00.00.00.00.00.00.00.00.c4}
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x50, address: 32fe95, target: 31185b, flags: 0x21, cmd1: 0x2e, cmd2: 0x00
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.topics] Topic: 32fe95.on_at_ramp_rate.direct_ack data: {'cmd1': 46, 'cmd2': 0, 'target': 31185b, 'user_data': None}
2020-04-13 08:08:14 DEBUG (MainThread) [pyinsteon.topics] Topic: 32fe95.extended_get_set.direct_ack data: {'cmd1': 46, 'cmd2': 0, 'target': 31185b, 'user_data': None}







[keypad_b]


2020-04-13 08:08:25 DEBUG (MainThread) [pyinsteon.topics] Topic: send.extended_get_set.direct data: {'address': 32fe95, 'priority': 5, 'data1': 1, 'data2': 9, 'data3': 8, 'data4': 0, 'data5': 0, 'data6': 0, 'data7': 0, 'data8': 0, 'data9': 0, 'data10': 0, 'data11': 0, 'data12': 0, 'data13': 0, 'data14': 0}
2020-04-13 08:08:25 DEBUG (MainThread) [pyinsteon.topics] Topic: send_message.extended_get_set data: {'msg': msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.08.00.00.00.00.00.00.00.00.00.00.c0, 'priority': 5}
2020-04-13 08:08:25 DEBUG (MainThread) [pyinsteon.messages] TX: msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.08.00.00.00.00.00.00.00.00.00.00.c0
2020-04-13 08:08:25 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x62, address: 32fe95, flags: 0x10, cmd1: 0x2e, cmd2: 0x00, user_data: 01.09.08.00.00.00.00.00.00.00.00.00.00.c0, ack: 0x06
2020-04-13 08:08:25 DEBUG (MainThread) [pyinsteon.topics] Topic: ack.32fe95.extended_get_set.direct data: {'cmd1': 46, 'cmd2': 0, 'user_data': 01.09.08.00.00.00.00.00.00.00.00.00.00.c0}
2020-04-13 08:08:27 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x50, address: 32fe95, target: 31185b, flags: 0x2b, cmd1: 0x2e, cmd2: 0x00
2020-04-13 08:08:27 DEBUG (MainThread) [pyinsteon.topics] Topic: 32fe95.on_at_ramp_rate.direct_ack data: {'cmd1': 46, 'cmd2': 0, 'target': 31185b, 'user_data': None}
2020-04-13 08:08:27 DEBUG (MainThread) [pyinsteon.topics] Topic: 32fe95.extended_get_set.direct_ack data: {'cmd1': 46, 'cmd2': 0, 'target': 31185b, 'user_data': None}

`

**Comment by jbarneson** [comment]
I upgraded HA again today, reinstalled pyinsteon, and updated your custom_component source to retest everything. And now the 6btn scene buttons are working correctly. I'll test more thoroughly and see if there are lingering problems

**Comment by jbarneson** [comment]
These seem to be working great, bidirectionally.

I think this is excpected behavior, but i'll post to validate, when i turn on `keypad_a` from HA, it lights up the keypad button... but it doesn't actually affect whatever devices `keypad_a` is configured to talk to. It just turns on the light. (i've seen this behavior in every instance of insteon control I've worked with, I think this is a limitation of the serial communication to the device) 

For `insteon2`, there's a bit of a side-effect that may or may not be something that can be controlled. It's a mouthful to explain though:

I turn on keypad_a from HA
the physical keypad_a lights up
if i turn off the physical keypad_a, HA does not reflect the state update
if i turn off keypad_a from HA, nothing happens physically
If i turn keypad_a on and off again from HA, I'm back in sync with the physical device
if i turn keypad_a back on and off from the physical device, i'm back in sync with HA

It's a minor problem for me as I mostly want to subscribe to button state updates for non-insteon actions in my automations. But in a few cases, I do set the state of these buttons from automation too.. in those cases, i'm going to leave the user in an un-intuitive stateless button interaction (if that's a good characterization).

Ideally -- even if downstream devices configured with teh keypad button were not notified on the insteon network -- the state of the button and it's next state updates would be respected on both sides. Do you think that's possible? or a limitation of insteon?

**Comment by teharris1** [comment]
Let me make sure I understand what you are saying. First you say:
> These seem to be working great, bidirectionally.

This would imply state changes in HA are reflected in the KPL and KPL changes are reflected in HA, all good. Thanks for that.  Then you make the statement:
> but it doesn't actually affect whatever devices keypad_a is configured to talk to

That is correct. It is an Insteon thing. There is a way you can have HA trigger the button in a way that also triggers the linked devices but there are other issues with that. Best approach is to trigger the button and all "linked" devices via automation in HA that way everybody is in sync.   This statement implies that the rest of this post is about the devices linked to a KPL button so I am going to make that assumption. Focusing on this statement:
> if i turn off the physical keypad_a, HA does not reflect the state update

This appears to be the crux of the issue. Given the question about the cascading changes above, I assume what this means is that the KPL button A changes the state of device2 but HA does not reflect the state update of Device2. Hopefully, that understanding is correct.  Please confirm this then I can respond better.

**Comment by jbarneson** [comment]
thanks for clarifying on point 2 being expected behavior -- accepted, and agreed... either using scenes on the modem to control groups of insteon devices, or HA automations is the workaround to the Insteon Network limitation.

to the last point -- keypad_a state update doesn't reflect back only in this series of events. If i just go through each of my keypad buttons locally, state updates work perfectly back in HA. Or if i only update states in HA, the keypad buttons update as expected.

But if i follow these steps: 
- I turn on keypad_a from HA
- the physical keypad_a lights up
- if i turn off the physical keypad_a, HA does not reflect the state update

That last step doesn't reflect back to HA because there seems to be a miscommuncation of what's happening. Could be related to that network limitation though -- but something to ponder. Does that clarification help?

**Comment by teharris1** [comment]
Thanks for the clarification. With your ALDB loaded for each device, your three-way switches should update in HA correctly as will the devices linked to your KPL buttons. But when you trigger a KPL button from HA there is no plan to have that change the state of the linked devices.  

Can you send me the logs from that sequence? I cannot recreate it but I only have an 8 button dimmer, not a 6 button switch so they are configured a little different.

**Comment by teharris1** [comment]
FYI, to post a log or code with multiple lines use three forward quotes ( ` ) on the first line and three on the last line. That will box the lines in between with no formatting.

**Comment by jbarneson** [comment]
went through and thoroughly tested all the scenarios around this case that I could and i can no longer reproduce the problem. Everything is working as designed, and working well.

The only thing i can think of that changed was the `insteon2.load_all_link_database`.. I'll let you comment if you have any follow up, otherwise I think we're good to close out the issue with the keypads working great
