### ISSUE TITLE
Insteon Thermostat Celsius vs Fahrenheit

### ISSUE THREAD

**Issue by doucga** [teharris1/insteon2#4]
I've updated pyinsteon using this command.

docker exec -it --user=root homeassistant pip3 install --upgrade https://github.com/teharris1/pyinsteon/archive/release1.zip

Hope that's right...

Restarted HA and got this in the log:

2020-04-13 19:18:59 ERROR (MainThread) [homeassistant.components.climate] Error while setting up insteon2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 380, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 181, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 490, in min_temp
    DEFAULT_MIN_TEMP, TEMP_CELSIUS, self.temperature_unit
  File "/config/custom_components/insteon2/climate.py", line 63, in temperature_unit
    if self._insteon_device.operating_flags[CELSIUS].value:
KeyError: 'celsius'

The thermostat is no longer available.

Hope this helps.

Garry

**Comment by teharris1** [comment]
I pushed an update this morning that should have addressed this issue.

**Comment by doucga** [comment]
Great, thank you! The update worked. Home Assistant is now consistently reporting Celsius.

However, Home Assistant still shows Celsius while my thermostat shows Farenheit.

Is that still a programming issue or is it a setting somewhere on my end?

Garry

**Comment by teharris1** [comment]
I cannot explain that one because mine is showing correctly. Just to be clear, are the numbers in Celsius and the units showing Celsius or is it that the numbers are showing Fahrenheit and the units are showing Celsius?

**Comment by doucga** [comment]
My apologies. I had units set to Celsius in the General Settings for Home Assistant. Switched it to Fahrenheit and now all is well.

Thanks for your help on this.

Garry
