### ISSUE TITLE
Unable to Load Insteon2 Custom Component

### ISSUE THREAD

**Issue by doucga** [teharris1/insteon2#8]
Hi Guys

Not sure what I did to my system but I'm now getting this when I check my configuration.

Log Details (ERROR)
Logger: homeassistant.loader
Source: custom_components/insteon2/__init__.py:5 
First occurred: 7:32:07 PM (2 occurrences) 
Last logged: 7:32:07 PM

Error loading custom_components.insteon2. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 391, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/insteon2/__init__.py", line 5, in <module>
    from pyinsteon import async_close, async_connect, devices
ModuleNotFoundError: No module named 'pyinsteon'

I followed the install instructions for insteon2 again but that didn't help. The only other thing I did recently was to upgrade to the latest Home Assistant 0.108.5.

Garry

**Comment by doucga** [comment]
I forgot I had to run:

docker exec -it --user=root homeassistant pip3 install --upgrade https://github.com/teharris1/pyinsteon/archive/release1.zip to get it going again.

Sorry I'm still learning about all this Docker stuff.

Might I suggest the docs get updated with the above for anyone running HA under Supervisor?

Thanks again for your work on this.

Garry
